#!/usr/bin/env -S python3 -u
from pathlib import Path

import click


@click.command()
@click.argument("file", metavar="FILE_NAME")
@click.help_option("-h", "--help")
def create_file(file):
    file_path = Path(file)
    file_path.parent.mkdir(parents=True, exist_ok=True)
    with file_path.open("w"):
        pass
    return 0


if __name__ == "__main__":
    create_file()
