#!/usr/bin/env -S python3 -u
import requests
import click


@click.command(name="docker-tags")
@click.argument("image")
def docker_tags(image):
    res = requests.get(f"https://registry.hub.docker.com/v1/repositories/{image}/tags")
    if res.status_code != 200:
        click.secho(
            f"there is error fetching tags for {image}: {res.text}[{res.status_code}]",
            fg="red",
            bold=True,
        )
        return 1
    click.secho(f"tags for {image} are:", fg="bright_green", bold=True)
    for tag in res.json():
        click.secho(f"{tag['name']}", fg="bright_blue")
    return 0


if __name__ == "__main__":
    docker_tags()
