#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function
import os
import argparse
import subprocess

def main(image_dir, surfixs, out_dir, verbose = False):
    subprocess.call(["mkdir", "-p", out_dir])
    out_path = os.path.abspath(out_dir)

    for current_dir, dirs, fnames in os.walk(image_dir):
        for fname in fnames:
            if any(list(map(fname.endswith, surfixs))):
                source_path = os.path.abspath(os.path.join(current_dir, fname))
                target_path = os.path.abspath(os.path.join(out_path, fname))
                if verbose:
                    print("moving {} to {}".format(source_path, target_path))
                subprocess.call(["cp", source_path, target_path])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--image-dir", "-d", help = "directory where to find images",
                        dest = "image_dir", required = True, metavar = "DIR_NAME")
    parser.add_argument("--surfixs", "-s", help = "surfixs of the images.",
                        dest = "surfixs", default = ["jpg", "png"], nargs = "+")
    parser.add_argument("--out-dir", "-o", help = "output directory",
                        dest = "out_dir", default = "images", metavar = "DIR_NAME")
    parser.add_argument("--verbose", "-v", help = "run in verbose mode",
                        action = "store_true", dest = "verbose")
    args = parser.parse_args()

    main(args.image_dir, args.surfixs, args.out_dir, args.verbose)
