#!/usr/bin/env -S python3 -u
import sys
from random import choices


def main():
    quotes = [line for line in sys.stdin.readlines() if not line.startswith("#")]
    print(choices(quotes, k=1)[0])


if __name__ == "__main__":
    main()
