#!/usr/bin/env -S python3 -u
# -*- coding: utf-8 -*-

"""
Rename all files and directories in a directory.

This program will replace specific characters in the filename with
desired characters. ex: replcae " " with "_".
"""

import os, argparse


def main(args):
    replace_str = args.replace_str
    with_str = args.with_str
    root_path = args.path
    verbose = args.verbose

    for current_dir, dirs, fnames in os.walk(root_path):
        for fname in fnames:
            if replace_str in fname:
                old_name = os.path.join(current_dir, fname)
                new_name = os.path.join(
                    current_dir, fname.replace(replace_str, with_str)
                )
                if verbose:
                    print("Rename {} to {}".format(old_name, new_name))
                os.rename(old_name, new_name)
        for dirname in dirs:
            if replace_str in dirname:
                old_name = os.path.join(current_dir, dirname)
                new_name = os.path.join(
                    current_dir, dirname.replace(replace_str, with_str)
                )
                if verbose:
                    print("Rename {} to {}".format(old_name, new_name))
                os.rename(old_name, new_name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="rename_by_replace", description=__doc__)
    parser.add_argument(
        "-r",
        "--replace",
        dest="replace_str",
        help="string in the file name to be replaced",
        metavar="STRING",
        default=" ",
    )
    parser.add_argument(
        "-w",
        "--with",
        dest="with_str",
        help="string to be replaced with",
        metavar="STRING",
        default="_",
    )
    parser.add_argument(
        "-p",
        "--path",
        help="path to the target directory.",
        metavar="PATH",
        dest="path",
        default=".",
    )
    parser.add_argument("-v", "--verbose", dest="verbose", action="store_true")
    args = parser.parse_args()
    main(args)
